config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "words#index" 
  resources :words do
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
self.data = [
  { id: 1, name: 'Category' },
  { id: 2, name: '名詞' },
  { id: 3, name: '代名詞' },
  { id: 4, name: '関係代名詞' },
  { id: 5, name: '動詞' },
  { id: 6, name: '他動詞' },
  { id: 7, name: '自動詞' },
  { id: 8, name: '助動詞' },
  { id: 9, name: '形容詞' },
  { id: 10, name: '副詞' },
  { id: 11, name: '前置詞' },
  { id: 12, name: '接続詞' },
  { id: 13, name: '感嘆詞' },
  { id: 14, name: '定冠詞' },
  { id: 15, name: '不定冠詞' },
  { id: 16, name: '接頭辞' },
  { id: 17, name: '接尾辞' },
  { id: 18, name: '連結詞' },
  { id: 19, name: '最上級' },
  { id: 20, name: '四文字熟語' },
  { id: 21, name: '諺' },
  { id: 22, name: 'その他' }
]

include ActiveHash::Associations
  has_many :words

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true, uniqueness: true
  
  has_many :words
end

app/models/validators/cantonese_validator.rb
class CantoneseValidator < ActiveModel::EachValidator

  def validate_each(record, attribute, value) # バリデーションメソッド
    if cantonese?(value)
      record.errors.add attribute, (options[:message] || "is not Fantizi")
      # record.errors.add(attribute, " は中国語ではありません。")
    end
  end

  CODEPOINTS =
  {
    japanese_kun: File.read("#{Rails.root}/app/models/concerns/japanese_kun"),
    japanese_on:  File.read("#{Rails.root}/app/models/concerns/japanese_on"),
    cantonese:    File.read("#{Rails.root}/app/models/concerns/cantonese"),
    mandarin:     File.read("#{Rails.root}/app/models/concerns/mandarin"),
  }.freeze

  # size == 1のStringをcodepointに変換する
  def to_codepoint(character)
    #raise "size == 1のStringを与える必要がある" unless character.size == 1
    character.codepoints.map{|cp| sprintf("%04X", cp)}.first
  end

  # 以下のように書きたいところだが重いので正規表現でやる
  # CODEPOINTS[:japanese_kun].include?(codepoint) # (CODEPOINTS[:japanese_kun]を配列にしておいた上で)
  def japanese_kun?(codepoint)
    !!(CODEPOINTS[:japanese_kun] =~ /\nU\+#{codepoint}\n/)
  end

  def japanese_on?(codepoint)
    !!(CODEPOINTS[:japanese_on] =~ /\nU\+#{codepoint}\n/)
  end

  def cantonese?(codepoint)
    !!(CODEPOINTS[:cantonese] =~ /\nU\+#{codepoint}\n/)
  end

  def mandarin?(codepoint)
    !!(CODEPOINTS[:mandarin] =~ /\nU\+#{codepoint}\n/)
  end

  # 漢字か判定
  def han?(character)
    character =~ /\p{Han}/
  end

  # 文字列から中国語らしき文字をselectする。
  # なぜか漢字以外のcodepointを与えると期待した動作をしないので、漢字のみで判定する。
  def select_chinese_and_not_japanese(survey_target_string)
    survey_target_string.split('').select do |character|
      next if !han?(character)

      codepoint = to_codepoint(character)
      next if japanese_kun?(codepoint) || japanese_on?(codepoint)
      next if !(cantonese?(codepoint) || mandarin?(codepoint))

      true
    end
  end
end

app/models/validators/mandarin_validator.rb
class MandarinValidator < ActiveModel::EachValidator

  def validate_each(record, attribute, value) # バリデーションメソッド
    if han?(value)
      record.errors.add attribute, (options[:message] || "is not Chinese")
      # record.errors.add(attribute, " は中国語ではありません。")
    end
  end

  CODEPOINTS =
  {
    japanese_kun: File.read("#{Rails.root}/app/models/concerns/japanese_kun"),
    japanese_on:  File.read("#{Rails.root}/app/models/concerns/japanese_on"),
    cantonese:    File.read("#{Rails.root}/app/models/concerns/cantonese"),
    mandarin:     File.read("#{Rails.root}/app/models/concerns/mandarin"),
  }.freeze

  # size == 1のStringをcodepointに変換する
  def to_codepoint(character)
    #raise "size == 1のStringを与える必要がある" unless character.size == 1
    character.codepoints.map{|cp| sprintf("%04X", cp)}.first
  end

  # 以下のように書きたいところだが重いので正規表現でやる
  # CODEPOINTS[:japanese_kun].include?(codepoint) # (CODEPOINTS[:japanese_kun]を配列にしておいた上で)
  def japanese_kun?(codepoint)
    !!(CODEPOINTS[:japanese_kun] =~ /\nU\+#{codepoint}\n/)
  end

  def japanese_on?(codepoint)
    !!(CODEPOINTS[:japanese_on] =~ /\nU\+#{codepoint}\n/)
  end

  def cantonese?(codepoint)
    !!(CODEPOINTS[:cantonese] =~ /\nU\+#{codepoint}\n/)
  end

  def mandarin?(codepoint)
    !!(CODEPOINTS[:mandarin] =~ /\nU\+#{codepoint}\n/)
  end

  # 漢字か判定
  def han?(character)
    character =~ /\p{Han}/
  end

  # 文字列から中国語らしき文字をselectする。
  # なぜか漢字以外のcodepointを与えると期待した動作をしないので、漢字のみで判定する。
  def select_chinese_and_not_japanese(survey_target_string)
    survey_target_string.split('').select do |character|
      next if !han?(character)

      codepoint = to_codepoint(character)
      next if japanese_kun?(codepoint) || japanese_on?(codepoint)
      next if !(cantonese?(codepoint) || mandarin?(codepoint))

      true
    end
  end
end

app/models/word.rb
class Word < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :user

  validates :category_id, numericality: { other_than: 1 , message: "can't be blank"}
  with_options presence: true do
  validates :jiantizi, format: {with: /\A[一-龥]+\z/, message: "is not Chinese" }
  validates :fantizi, format: {with: /\A[一-龥]+\z/, message: "is not Chinese" }
  validates :pronunciation_c
  end
  validates :english, format: {with: /\A[a-zA-Z0-9]+\z/}

  def self.search(search)
    if search != ""
      Word.where('pronunciation_c LIKE(?)', "%#{search}%").or Word.where('english LIKE(?)', "%#{search}%").or Word.where('fantizi LIKE(?)', "%#{search}%").or Word.where('jiantizi LIKE(?)', "%#{search}%")
    else
      Word.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:destroy, :edit, :update, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @words = Word.all.order(:pronunciation_c)
    @words = Word.includes(:user)
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.create(word_params)
    if @word.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @word.destroy
  end

  def edit
    if current_user.id != @word.user_id
      redirect_to root_path
    end
  end

  def update
    if @word.update(word_params)
      redirect_to word_path(@word.id)
    else
      render :edit
    end
  end

  def show
  end

  def search
    @words = Word.search(params[:keyword])
    if @words != nil
      render :index
    end
  end

  private
  def word_params
    params.require(:word).permit(:jiantizi, :fantizi, :english, :pronunciation_c, :pronunciation_e, :category_id, :mean, :memo).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def set_word
    @word = Word.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>dictionary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<body>
  <header class="header">
      <h1 class="grid-6">WordList</h1>
      <% if user_signed_in? %>
      <div class="grid-6">
      <span><%= link_to "#{current_user.nickname}の単語帳", root_path, class:"post" %>
          <%= link_to "単語登録", new_word_path, class: "post" %>    
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "post" %>
      </span>
      </div>
    <% else %>
      <div class="grid-6">
        <%= link_to "ログイン", new_user_session_path, class: "post" %>
        <%= link_to "新規登録", new_user_registration_path, class: "post" %>
      </div>
    <% end %>
    </div>
  </header>
    <%= yield %>
    <footer>
      <p>
      </p>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/words/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">一覧へ戻る</a>
  </div>
</div>

app/views/words/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>登録</h3>
    <%= form_with(model: @word, local: true) do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      <%= f.text_field :jiantizi, placeholder: "简体字" %>
      <%= f.text_field :fantizi, placeholder: "繁体字" %>
      <%= f.text_field :pronunciation_c, placeholder: "发音" %>
      <%= f.text_field :english, placeholder: "English" %>
      <%= f.text_field :pronunciation_e, placeholder: "Pronunciation" %>
      <%= f.text_area :mean, placeholder: "意思", rows: "5" %>
      <%= f.text_area :memo, placeholder: "memo", rows: "5" %>
      <%= f.submit "登録" %>
    <% end %>
  </div>
</div>

app/views/words/index.html.erb
<div class="wrapper">
    <div class="search">
      <%= form_with(url: search_words_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "単語を検索", class: "search-input" %>
      <%= form.submit "Search", class: "search-btn" %>
      <% end %>
    </div>
  <% @words.each do |word| %>
    <%= link_to word_path(word.id) do %>
      <li>
        <%= word.jiantizi %><%= word.pronunciation_c %>
      </li>
    <% end %>
  <% end %>
</div>

app/views/words/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>登録</h3>
    <%= form_with(model: @word, local: true) do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      <%= f.text_field :jiantizi, placeholder: "简体字" %>
      <%= f.text_field :fantizi, placeholder: "繁体字" %>
      <%= f.text_field :pronunciation_c, placeholder: "发音" %>
      <%= f.text_field :english, placeholder: "English" %>
      <%= f.text_field :pronunciation_e, placeholder: "Pronunciation" %>
      <%= f.text_area :mean, placeholder: "意思", rows: "5" %>
      <%= f.text_area :memo, placeholder: "memo", rows: "5" %>
      <%= f.submit "登録" %>
    <% end %>
  </div>
</div>

app/views/words/search.html.erb
<%= form_with(url: search_words_path, local: true, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "単語を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @words.each do |word| %>
    <li>
    <%= link_to word.jiantizi, word_path(word.id) %>
    <%= word.pronunciation_c %>
  </li>
  <% end %>
</div>

app/views/words/show.html.erb
  <% if user_signed_in? && current_user.id == @word.user_id %>
  <%= link_to "編集", edit_word_path(@word.id), class: "item-red-btn" %>
  <%= link_to "削除", word_path(@word.id), method: :delete, class: "item-red-btn" %>
  <% end %>
  <%= link_to "一覧に戻る", root_path(@word.id) ,class: "item-red-btn"%>

    <table class="detail-table">
      <tbody>
         <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @word.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @word.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">简体字</th>
          <td class="detail-value"><%= @word.jiantizi %></td>
        </tr>
        <tr>
          <th class="detail-item">繁体字</th>
          <td class="detail-value"><%= @word.fantizi %></td>
        </tr>
        <tr>
          <th class="detail-item">发音</th>
          <td class="detail-value"><%= @word.pronunciation_c %></td>
        </tr>
        <tr>
          <th class="detail-item">English</th>
          <td class="detail-value"><%= @word.english %></td>
        </tr>
        <tr>
          <th class="detail-item">Pronunciation</th>
          <td class="detail-value"><%= @word.pronunciation_e %></td>
        </tr>
        <tr>
          <th class="detail-item">意味</th>
          <td class="detail-value"><%= @word.mean %></td>
        </tr>
        <tr>
          <th class="detail-item">メモ</th>
          <td class="detail-value"><%= @word.memo %></td>
        </tr>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= @word.user.nickname %></td>
        </tr>
      </tbody>
    </table>

app/views/words/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新完了</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>